### ISSUE TITLE
cherry_picker executable script is broken

### ISSUE THREAD

**Issue by pitrou** [python/cherry-picker#26]
I just installed cherry_picker 2.0.0 in a conda environment and I get the following error when trying to run it:
```bash
$ cherry_picker --help
Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/cherry_picker/bin/cherry_picker", line 5, in <module>
    from cherry_picker import cherry_pick_cli
ImportError: cannot import name 'cherry_pick_cli' from 'cherry_picker' (/home/antoine/miniconda3/envs/cherry_picker/lib/python3.9/site-packages/cherry_picker/__init__.py)
```
Installed packages:
```bash
$ pip list
Package       Version
------------- -------------------
certifi       2020.12.5
cffi          1.14.5
chardet       4.0.0
cherry-picker 2.0.0
click         8.0.0
cryptography  3.4.7
gidgethub     5.0.1
idna          2.10
pip           21.0.1
pycparser     2.20
PyJWT         2.1.0
requests      2.25.1
setuptools    52.0.0.post20210125
toml          0.10.2
uritemplate   3.0.1
urllib3       1.26.4
wheel         0.36.2
```

**Comment by pitrou** [comment]
`python -m cherry_picker` does work, but if a `cherry_picker` executable script is installed, I would expect it to work as well.

**Comment by Mariatta** [comment]
Hmm I'm not familiar with how conda work, so maybe someone else can help with this issue?

**Comment by gpshead** [comment]
This issue has nothing to do with conda, just make a venv and try to run cherry_picker:

```
python3 -m venv toolenv
. toolenv/bin/activate
pip install cherry_picker
cherry_picker
```

```
(toolenv) ➜  oss/python/gpshead git:(main) cherry_picker
Traceback (most recent call last):
  File "/.../toolenv/bin/cherry_picker", line 5, in <module>
    from cherry_picker import cherry_pick_cli
ImportError: cannot import name 'cherry_pick_cli' from 'cherry_picker' (/.../toolenv/lib/python3.8/site-packages/cherry_picker/__init__.py)
```

Thanks for the PR jaraco!

**Comment by orsenthil** [comment]
I encountered this today.  Cherry-picker package update with this fix might help.

```

(cpython) [senthilx@88665a371033:~/git/cpython]$ python --version
Python 3.11.0a0

$ pip install cherry-picker
Collecting cherry-picker
  Using cached cherry_picker-2.0.0-py3-none-any.whl (22 kB)
Requirement already satisfied: click>=6.0 in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages (from cherry-picker) (8.0.1)
Requirement already satisfied: requests in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages/requests-2.26.0-py3.11.egg (from cherry-picker) (2.26.0)
Requirement already satisfied: gidgethub in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages (from cherry-picker) (5.0.1)
Requirement already satisfied: toml in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages (from cherry-picker) (0.10.2)
Requirement already satisfied: PyJWT[crypto]>=2.0.0 in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages (from gidgethub->cherry-picker) (2.1.0)
Requirement already satisfied: uritemplate>=3.0.1 in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages (from gidgethub->cherry-picker) (3.0.1)
Requirement already satisfied: cryptography<4.0.0,>=3.3.1 in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages (from PyJWT[crypto]>=2.0.0->gidgethub->cherry-picker) (3.4.8)
Requirement already satisfied: cffi>=1.12 in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages (from cryptography<4.0.0,>=3.3.1->PyJWT[crypto]>=2.0.0->gidgethub->cherry-picker) (1.14.6)
Requirement already satisfied: pycparser in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages (from cffi>=1.12->cryptography<4.0.0,>=3.3.1->PyJWT[crypto]>=2.0.0->gidgethub->cherry-picker) (2.20)
Requirement already satisfied: certifi>=2017.4.17 in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages/certifi-2021.5.30-py3.11.egg (from requests->cherry-picker) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages/charset_normalizer-2.0.4-py3.11.egg (from requests->cherry-picker) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages/idna-3.2-py3.11.egg (from requests->cherry-picker) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/senthilx/venvs/cpython/lib/python3.11/site-packages/urllib3-1.26.6-py3.11.egg (from requests->cherry-picker) (1.26.6)
Installing collected packages: cherry-picker
Successfully installed cherry-picker-2.0.0

(cpython) [senthilx@88665a371033:~/git/cpython]$ cherry_picker
Traceback (most recent call last):
  File "/Users/senthilx/venvs/cpython/bin/cherry_picker", line 5, in <module>
    from cherry_picker import cherry_pick_cli
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'cherry_pick_cli' from 'cherry_picker' (/Users/senthilx/venvs/cpython/lib/python3.11/site-packages/cherry_picker/__init__.py)


```

**Comment by orsenthil** [comment]
I reopened this ticket as I assumed pip install is the only way to use cherry-picker (other than copying files since I didn't see setup.py).

I later notice the use of Flit to do a local installation, I will try that. Please close the bug or leave it open as you (the maintainer) sees it fit. Thank you.

**Comment by jaraco** [comment]
One way you can run cherry-picker without the script (or any virtualenv) is to use [pip-run](https://pypi.org/project/pip-run):

```
~ $ pip-run -q cherry-picker -- -m cherry_picker --help
Usage: python -m cherry_picker [OPTIONS] [COMMIT_SHA1] [BRANCHES]...

  cherry-pick COMMIT_SHA1 into target BRANCHES.

Options:
  --version                  Show the version and exit.
  --dry-run                  Prints out the commands, but not executed.
  --pr-remote REMOTE         git remote to use for PR branches
  --abort                    Abort current cherry-pick and clean up branch
  --continue                 Continue cherry-pick, push, and clean up branch
  --status                   Get the status of cherry-pick
  --push / --no-push         Changes won't be pushed to remote
  --config-path CONFIG-PATH  Path to config file, .cherry_picker.toml from
                             project root by default. You can prepend a colon-
                             separated Git 'commitish' reference.
  -h, --help                 Show this message and exit.
```

The problem you're encountering is that [the fix](https://github.com/python/cherry-picker/commit/f02b68c648ad88be74d88a959b78cd0a604f8993) isn't yet incorporated in any release. To get a version of cherry_picker that works, you need to install from main for now:

```
pip install git+https://github.com/python/cherry-picker
```

Happy to leave this issue open until a release can be made.

**Comment by orsenthil** [comment]
TIL about two projects pip-run and Flit. :-)

**Comment by jaraco** [comment]
With the release of 2.1.0 (https://github.com/python/cherry-picker/issues/53#issuecomment-965524906), this issue is solved.

**Comment by pitrou** [comment]
Thank you!
