### ISSUE TITLE
CalledProcessError on git checkout master

### ISSUE THREAD

**Issue by jaraco** [python/cherry-picker#27]
After running cherry_picker (2.0, latest release), I get this output ending with a traceback:

```
$ cherry_picker --continue
🐍 🍒 ⛏
remote: 
remote: Create a pull request for 'backport-23acadc-3.9' on GitHub by visiting:        
remote:      https://github.com/python/cpython/pull/new/backport-23acadc-3.9        
remote: 
To https://github.com/python/cpython
 * [new branch]            backport-23acadc-3.9 -> backport-23acadc-3.9

Backport PR URL:
https://github.com/python/cpython/compare/3.9...python:backport-23acadc-3.9?expand=1
Traceback (most recent call last):
  File "/Users/jaraco/.local/bin/cherry_picker", line 8, in <module>
    sys.exit(cherry_pick_cli())
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/cherry_picker/cherry_picker.py", line 615, in cherry_pick_cli
    cherry_picker.continue_cherry_pick()
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/cherry_picker/cherry_picker.py", line 473, in continue_cherry_pick
    self.cleanup_branch(cherry_pick_branch)
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/cherry_picker/cherry_picker.py", line 349, in cleanup_branch
    self.checkout_default_branch()
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/cherry_picker/cherry_picker.py", line 221, in checkout_default_branch
    self.run_cmd(cmd)
  File "/Users/jaraco/.local/pipx/venvs/cherry_picker/lib/python3.9/site-packages/cherry_picker/cherry_picker.py", line 180, in run_cmd
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('git', 'checkout', 'master')' returned non-zero exit status 1.
```

I suspect the issue is that `master` is no longer a branch in the repo and it should be `main`.

**Comment by jaraco** [comment]
Oh, I think it may be a bug in pipx. I'd `pipx upgrade cherry_picker`, and it said it did, but `cherry_picker --version` shows 1.3.2.

**Comment by jaraco** [comment]
Ah yes, a bug in mangled names:

```
cpython main $ pipx upgrade cherry_picker
⚠️  File exists at /Users/jaraco/.local/bin/cherry_picker and points to /Users/jaraco/.local/pipx/venvs/cherry_picker/bin/cherry_picker, not
    /Users/jaraco/.local/pipx/venvs/cherry-picker/bin/cherry_picker. Not modifying.
upgraded package cherry-picker from 1.3.2 to 2.0.0 (location: /Users/jaraco/.local/pipx/venvs/cherry-picker)
cherry-picker main $ pipx upgrade cherry_picker
cherry-picker is already at latest version 2.0.0 (location: /Users/jaraco/.local/pipx/venvs/cherry-picker)
⚠️  File exists at /Users/jaraco/.local/bin/cherry_picker and points to /Users/jaraco/.local/pipx/venvs/cherry_picker/bin/cherry_picker, not
    /Users/jaraco/.local/pipx/venvs/cherry-picker/bin/cherry_picker. Not modifying.
```

**Comment by jaraco** [comment]
After working around the pipx bug, now cherry_picker doesn't work at all:

```
cherry-picker main $ pipx uninstall cherry_picker
uninstalled cherry-picker! ✨ 🌟 ✨

cherry-picker main $ pipx uninstall cherry-picker
Nothing to uninstall for cherry-picker 😴
cherry-picker main $ pipx uninstall cherry_picker
Nothing to uninstall for cherry-picker 😴
cherry-picker main $ ls ~/.local/bin/cherry*
/Users/jaraco/.local/bin/cherry_picker
cherry-picker main $ ls -la ~/.local/bin/cherry*
lrwxr-xr-x  1 jaraco  staff  63 Oct  6  2020 /Users/jaraco/.local/bin/cherry_picker -> /Users/jaraco/.local/pipx/venvs/cherry_picker/bin/cherry_picker
cherry-picker main $ rm ~/.local/bin/cherry_picker
cherry-picker main $ pipx install cherry-picker
done! ✨ 🌟 ✨herry-picker
  installed package cherry-picker 2.0.0, Python 3.9.2
  These apps are now globally available
    - cherry_picker
cherry-picker main $ cherry_picker --version
Traceback (most recent call last):
  File "/Users/jaraco/.local/bin/cherry_picker", line 5, in <module>
    from cherry_picker import cherry_pick_cli
ImportError: cannot import name 'cherry_pick_cli' from 'cherry_picker' (/Users/jaraco/.local/pipx/venvs/cherry-picker/lib/python3.9/site-packages/cherry_picker/__init__.py)
```

**Comment by jaraco** [comment]
The latter issue is #26, so closing.
